const pad = (value) => String(value).padStart(2, "0");

const dateAt = (offsetDays, hour = 10, minute = 0) => {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString();
};

const shortDate = (offsetDays) => {
  const date = new Date();
  date.setDate(date.getDate() + offsetDays);
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
};

export const STORAGE_KEY = "community-alliance-demo-v1";

export const createSeedState = (siteName = "Your Community Now") => ({
  version: 1,
  config: {
    setupComplete: Boolean(siteName && siteName !== "Your Community Now"),
    siteName,
    tagline: "What's New. What's On. What's Next.",
  },
  savedEventIds: [],
  notifications: [
    {
      id: "notice-1",
      title: "Welcome to the sandbox",
      body: "Everything you change here stays in this browser and can be reset at any time.",
      createdAt: new Date().toISOString(),
      read: false,
    },
  ],
  organisations: [
    {
      id: "sample-community-council",
      name: "Sample Community Council",
      category: "Community",
      short: "A fictional local community body used only to demonstrate how organisation profiles work.",
      email: "hello@example.invalid",
      phone: "01234 000001",
      website: "https://example.invalid/sample-community-council",
      claimed: true,
      admins: ["demo.admin@example.invalid"],
    },
    {
      id: "example-youth-collective",
      name: "Example Youth Collective",
      category: "Young people",
      short: "A made-up youth group showing how clubs and voluntary organisations can appear on the platform.",
      email: "youth@example.invalid",
      phone: "01234 000002",
      website: "https://example.invalid/youth",
      claimed: false,
      admins: [],
    },
    {
      id: "demo-heritage-group",
      name: "Demo Heritage Group",
      category: "Heritage",
      short: "A fictional heritage group with sample events and community updates.",
      email: "heritage@example.invalid",
      phone: "01234 000003",
      website: "https://example.invalid/heritage",
      claimed: true,
      admins: ["heritage.admin@example.invalid"],
    },
    {
      id: "sandbox-gardening-club",
      name: "Sandbox Gardening Club",
      category: "Hobbies",
      short: "A fictional gardening club used to demonstrate recurring activities and volunteering opportunities.",
      email: "garden@example.invalid",
      phone: "01234 000004",
      website: "https://example.invalid/garden",
      claimed: false,
      admins: [],
    },
    {
      id: "community-wellbeing-network",
      name: "Community Wellbeing Network",
      category: "Health & wellbeing",
      short: "A synthetic example showing how support, wellbeing and community organisations can be listed.",
      email: "wellbeing@example.invalid",
      phone: "01234 000005",
      website: "https://example.invalid/wellbeing",
      claimed: true,
      admins: ["wellbeing.admin@example.invalid"],
    },
  ],
  venues: [
    {
      id: "demo-community-hall",
      name: "Demo Community Hall",
      address: "1 Example Street, Demo Area",
      facilities: ["Accessible entrance", "Kitchen", "Wi-Fi"],
      capacity: 120,
    },
    {
      id: "example-library-room",
      name: "Example Library Room",
      address: "2 Sample Lane, Demo Area",
      facilities: ["Accessible toilet", "Projector", "Quiet space"],
      capacity: 40,
    },
    {
      id: "sample-sports-pavilion",
      name: "Sample Sports Pavilion",
      address: "3 Fictional Avenue, Demo Area",
      facilities: ["Changing rooms", "Parking", "Outdoor space"],
      capacity: 80,
    },
    {
      id: "sandbox-green",
      name: "Sandbox Green",
      address: "Central Demo Green, Demo Area",
      facilities: ["Outdoor space", "Benches", "Open access"],
      capacity: null,
    },
  ],
  events: [
    {
      id: "evt-welcome-coffee",
      title: "Sample Welcome Coffee Morning",
      orgId: "sample-community-council",
      venueId: "demo-community-hall",
      start: dateAt(3, 10, 0),
      end: dateAt(3, 12, 0),
      category: "Community",
      fee: "Free",
      description: "A fictional coffee morning used to demonstrate event listings, saving and detail pages.",
      featured: true,
      status: "published",
    },
    {
      id: "evt-family-day",
      title: "Demo Family Activity Day",
      orgId: "example-youth-collective",
      venueId: "sandbox-green",
      start: dateAt(6, 11, 0),
      end: dateAt(6, 15, 0),
      category: "Family",
      fee: "Free",
      description: "A synthetic family event with games, crafts and activities for the purposes of this sandbox only.",
      featured: true,
      status: "published",
    },
    {
      id: "evt-heritage-walk",
      title: "Example Heritage Walk",
      orgId: "demo-heritage-group",
      venueId: "example-library-room",
      start: dateAt(9, 13, 30),
      end: dateAt(9, 15, 0),
      category: "Heritage",
      fee: "£3 sample fee",
      description: "A fictional guided walk demonstrating paid events, organiser profiles and venue links.",
      featured: false,
      status: "published",
    },
    {
      id: "evt-garden-workshop",
      title: "Sandbox Growing Workshop",
      orgId: "sandbox-gardening-club",
      venueId: "demo-community-hall",
      start: dateAt(12, 18, 30),
      end: dateAt(12, 20, 0),
      category: "Hobbies",
      fee: "Free",
      description: "A fictional evening workshop showing how hobby groups can publish activities.",
      featured: false,
      status: "published",
    },
    {
      id: "evt-wellbeing",
      title: "Sample Wellbeing Drop-In",
      orgId: "community-wellbeing-network",
      venueId: "example-library-room",
      start: dateAt(16, 14, 0),
      end: dateAt(16, 16, 0),
      category: "Health & wellbeing",
      fee: "Free",
      description: "A fictional wellbeing session included only to demonstrate another category of community listing.",
      featured: false,
      status: "published",
    },
    {
      id: "evt-fair",
      title: "Sample Community Fair",
      orgId: "sample-community-council",
      venueId: "sandbox-green",
      start: dateAt(24, 11, 0),
      end: dateAt(24, 16, 0),
      category: "Community",
      fee: "Free",
      description: "A fictional larger event used to show a prominent What's On listing.",
      featured: true,
      status: "published",
    },
  ],
  volunteering: [
    {
      id: "vol-event-helper",
      title: "Sample Event Helper",
      orgId: "sample-community-council",
      time: "2–3 hours occasionally",
      age: "16+",
      description: "Help welcome visitors and support fictional community events in this demo.",
    },
    {
      id: "vol-youth-helper",
      title: "Example Youth Activity Volunteer",
      orgId: "example-youth-collective",
      time: "One evening a month",
      age: "18+",
      description: "A synthetic opportunity demonstrating how volunteer vacancies can be advertised.",
    },
    {
      id: "vol-garden",
      title: "Sandbox Garden Volunteer",
      orgId: "sandbox-gardening-club",
      time: "Flexible",
      age: "All ages with supervision",
      description: "A fictional gardening role included for sandbox exploration only.",
    },
    {
      id: "vol-digital",
      title: "Demo Digital Support Volunteer",
      orgId: "community-wellbeing-network",
      time: "Around 2 hours a month",
      age: "18+",
      description: "Help people with basic digital tasks in this fictional example role.",
    },
  ],
  feed: [
    {
      id: "feed-1",
      orgId: "sample-community-council",
      title: "Welcome to the community sandbox",
      body: "This is a fictional update. Try creating, editing and deleting content from Sandbox Studio to see how a local platform could work.",
      createdAt: dateAt(-1, 9, 0),
      likes: 8,
    },
    {
      id: "feed-2",
      orgId: "example-youth-collective",
      title: "Sample volunteers wanted",
      body: "Our fictional youth group is looking for demo volunteers. Open the volunteering area to see how opportunities are presented.",
      createdAt: dateAt(-2, 16, 0),
      likes: 5,
    },
    {
      id: "feed-3",
      orgId: "demo-heritage-group",
      title: "Example archive project",
      body: "A synthetic community-history update showing how organisations can keep residents informed between events.",
      createdAt: dateAt(-4, 11, 30),
      likes: 12,
    },
    {
      id: "feed-4",
      orgId: "sandbox-gardening-club",
      title: "Sandbox growing season begins",
      body: "This made-up post demonstrates day-to-day local news and updates from participating groups.",
      createdAt: dateAt(-6, 8, 45),
      likes: 3,
    },
  ],
  meta: {
    createdAt: new Date().toISOString(),
    fictionalOnly: true,
    seedDate: shortDate(0),
  },
});

export const uid = (prefix) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
